### ISSUE TITLE
TypeScript typings issue

### ISSUE THREAD

**Issue by peterjuras** [n8tb1t/use-scroll-position#10]
Hi!

First of all thank you for creating this hook, it really adds a lot of value!

The TypeScript types appear to have some issues. The x and y coordinates should use `number` instead of the upper-case `Number` to allow for arithmetic operations.

I can create a pull request if you'd like.

Best regards,
Peter

**Comment by n8tb1t** [comment]
@peterjuras Thanks, sure, go for it, I'll be glad to merge it.
