### ISSUE TITLE
Does not work in IE11

### ISSUE THREAD

**Issue by agonsalves** [n8tb1t/use-scroll-position#12]
The methods this uses to get scroll position are not compatible with IE11.

**Comment by n8tb1t** [comment]
Hi, have you tried setting `useWindow` to `true` ?

**Comment by n8tb1t** [comment]
If it still doesn't work, you can add an option to enable IE11 support and make a PR, I'll be glad to accept the feature :)

**Comment by agonsalves** [comment]
Yes, I have tried the option.

If I knew how to resolve it, I'd gladly submit an PR, but if it cannot be fixed, at least list the browser compatibility in the Read Me.

**Comment by ecjs** [comment]
@agonsalves , just passing through...but maybe think about submitting a PR to update the readme if you don't like it.  Open source = free.

**Comment by n8tb1t** [comment]
The module should work in IE9-11, the ticket is closed until further validation that the bug is indeed present!
https://dev.to/n8tb1t/tracking-scroll-position-with-react-hooks-3bbj
