### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by skyburchard** [n8tb1t/use-scroll-position#13]
I'm new to react hooks, so I could very well be doing something wrong, but I cannot get even the console.log example to work. I'm using gatsby and react 16.12.0. I have a page called "scrollPage". the code is pasted below:

```
import React from "react";
import useScrollPosition from "use-scroll-position";

const ScrollPage = () => {
  useScrollPosition(({prevPos, currPos}) => {
    console.log(currPos.x);
    console.log(currPos.y);
  }, [], false, true, 10);

  return (
    <div>
      <div>Hello Scroll Position</div>
      <div style={{height: "2000px"}}></div>
    </div>
  )
}

export default ScrollPage;
```

I don't get any errors, just not logs to console. This hook is really convenient. Would love to get it working.

**Comment by hadri3n** [comment]
Are you sure you are using this library here ?

Your import is not right at least, it should be:
```javascript
import { useScrollPosition } from '@n8tb1t/use-scroll-position'
```

Make sure you installed the proper library as written in the README: 
`yarn add @n8tb1t/use-scroll-position`

**Comment by n8tb1t** [comment]
Yes, as @hadri3n  pointed out, it looks like you are using the wrong lib, just change the `import` and let us know how it goes.

**Comment by skyburchard** [comment]
Ha! I WAS using the wrong package. I must have blindly assumed that i should install using "npm install use-scroll-position" and it was just a coincidence that a package by that name already exists. That package sets state though, which is not what I want. Thanks for pointing that out! It's working now.
