### ISSUE TITLE
`getBoundingClientRect` is called even when `useWindow: true`

### ISSUE THREAD

**Issue by OliverJAsh** [n8tb1t/use-scroll-position#19]
It seems that `getBoundingClientRect` is called even when `useWindow` is `true`.

https://github.com/n8tb1t/use-scroll-position/blob/c5d538b981d9521fefd86c37c0024a7a8c17f7b2/src/useScrollPosition.jsx#L11-L15

I think we only want to call `getBoundingClientRect` if `useWindow` is `false`? IIUC, `getBoundingClientRect` will force layout, whereas `window.scroll{X,Y}` will not.

**Comment by n8tb1t** [comment]
God catch! fixed !
