### ISSUE TITLE
useScrollPosition throws when window is not defined

### ISSUE THREAD

**Issue by rumtraubenuss** [n8tb1t/use-scroll-position#3]
In my jest test environment there is no window. So `useScrollPosition` throws with `ReferenceError: window is not defined`. See #2.

**Comment by rumtraubenuss** [comment]
@n8tb1t ping ☝️🙃

**Comment by n8tb1t** [comment]
Oh, sorry I missed the initial issue. Thank you very much for fixing it, I'll update the NPM ASAP.

**Comment by rumtraubenuss** [comment]
@n8tb1t Could you already publish the update to npm?

**Comment by n8tb1t** [comment]
done
