### ISSUE TITLE
Type 'undefined' is not assignable to type 'HTMLElement'

### ISSUE THREAD

**Issue by jonwalz** [n8tb1t/use-scroll-position#30]
Hey, awesome hook. 

Having a small type issue and wondering if somehow I am just using it wrong. 

Error is: `Argument of type 'MutableRefObject<undefined>' is not assignable to parameter of type 'MutableRefObject<HTMLElement>'.
  Type 'undefined' is not assignable to type 'HTMLElement'.ts(2345)`

I'm seeing this in a personal project but made a simple codesandbox to demonstrate the issue:
https://codesandbox.io/s/pensive-elion-ined1

Thanks!

**Comment by n8tb1t** [comment]
Fixed in v2.0.3
