### ISSUE TITLE
Make it available on npm

### ISSUE THREAD

**Issue by raulrene** [n8tb1t/use-scroll-position#9]
First of all, congrats on the module. Found it on dev.to and the code is really clean. You should make it available on npm as well.

**Comment by n8tb1t** [comment]
@raulrene Thank you very much for the kind words, this is only thanks to contributions from people like yourself, who constantly improve it  :) And it is available on NPM 
- https://www.npmjs.com/package/@n8tb1t/use-scroll-position

**Comment by raulrene** [comment]
Sorry for that. Maybe update the README s.t. it reflects this. There's another one with the same name on npm and it's helpful to have it in the documentation
